/** Mapa de tradução: nome em inglês → nome em português */
const teamNamesPtBR: Record<string, string> = {
  "Afghanistan": "Afeganistão",
  "Albania": "Albânia",
  "Algeria": "Argélia",
  "Angola": "Angola",
  "Argentina": "Argentina",
  "Australia": "Austrália",
  "Austria": "Áustria",
  "Bahrain": "Barein",
  "Belgium": "Bélgica",
  "Bolivia": "Bolívia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  "Brazil": "Brasil",
  "Cape Verde": "Cabo Verde",
  "Cameroon": "Camarões",
  "Canada": "Canadá",
  "Chile": "Chile",
  "China PR": "China",
  "Colombia": "Colômbia",
  "Congo DR": "RD Congo",
  "Democratic Republic of the Congo": "RD Congo",
  "Costa Rica": "Costa Rica",
  "Croatia": "Croácia",
  "Czech Republic": "República Tcheca",
  "Denmark": "Dinamarca",
  "Ecuador": "Equador",
  "Egypt": "Egito",
  "England": "Inglaterra",
  "Finland": "Finlândia",
  "France": "França",
  "Germany": "Alemanha",
  "Ghana": "Gana",
  "Greece": "Grécia",
  "Honduras": "Honduras",
  "Hungary": "Hungria",
  "Iceland": "Islândia",
  "India": "Índia",
  "Indonesia": "Indonésia",
  "Iran": "Irã",
  "Iraq": "Iraque",
  "Ireland": "Irlanda",
  "Israel": "Israel",
  "Italy": "Itália",
  "Ivory Coast": "Costa do Marfim",
  "Jamaica": "Jamaica",
  "Japan": "Japão",
  "Jordan": "Jordânia",
  "Kenya": "Quênia",
  "Korea Republic": "Coreia do Sul",
  "South Korea": "Coreia do Sul",
  "Mali": "Mali",
  "Mexico": "México",
  "Morocco": "Marrocos",
  "Netherlands": "Holanda",
  "New Zealand": "Nova Zelândia",
  "Nigeria": "Nigéria",
  "North Macedonia": "Macedônia do Norte",
  "Norway": "Noruega",
  "Oman": "Omã",
  "Panama": "Panamá",
  "Paraguay": "Paraguai",
  "Peru": "Peru",
  "Poland": "Polônia",
  "Portugal": "Portugal",
  "Qatar": "Catar",
  "Romania": "Romênia",
  "Russia": "Rússia",
  "Saudi Arabia": "Arábia Saudita",
  "Scotland": "Escócia",
  "Senegal": "Senegal",
  "Serbia": "Sérvia",
  "Slovakia": "Eslováquia",
  "Slovenia": "Eslovênia",
  "South Africa": "África do Sul",
  "Spain": "Espanha",
  "Sweden": "Suécia",
  "Switzerland": "Suíça",
  "Trinidad and Tobago": "Trinidad e Tobago",
  "Tunisia": "Tunísia",
  "Turkey": "Turquia",
  "Ukraine": "Ucrânia",
  "United Arab Emirates": "Emirados Árabes",
  "United States": "Estados Unidos",
  "Uruguay": "Uruguai",
  "Uzbekistan": "Uzbequistão",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnã",
  "Wales": "País de Gales",
};

/** Traduz nome do time para português. Se não encontrar, retorna o original. */
export function translateTeamName(name: string): string {
  return teamNamesPtBR[name] || name;
}
